name: CI/CD for C++ Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24'

      - name: Build the project
        env:
          PLATFORM: 'Web'
          BUILD_TYPE: 'Release'
        run: |
          cmake -S . -B cmake-build-${{ env.BUILD_TYPE }} -DPLATFORM=${{ env.PLATFORM }}
          cmake --build cmake-build-${{ env.BUILD_TYPE }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: cmake-build-*/index.*
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy build artifacts
        run: cp -r cmake-build-*/index.* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
